FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache \
    git \
    docker-cli \
    docker-cli-buildx

COPY package*.json ./

RUN npm ci

COPY tsconfig.json ./
COPY src ./src

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/workers/deploymentWorker.js"]
